#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
app="$root/app.js"
styles="$root/styles.css"

rg -Fq 'function ensureVirtualAssistantChat()' "$app"
rg -Fq 'function positionVirtualAssistantChat(panel)' "$app"
rg -Fq 'window.addEventListener("resize", () => positionVirtualAssistantChat(panel))' "$app"
rg -Fq 'if (openVirtualAssistant && !openVirtualAssistant.hidden) positionVirtualAssistantChat(openVirtualAssistant);' "$app"
rg -Fq 'data-virtual-assistant-chat' "$app"
rg -Fq 'data-virtual-assistant-chat-close' "$app"
rg -Fq 'data-virtual-assistant-chat-new' "$app"
rg -Fq 'data-dashboard-virtual-assistant' "$app"
rg -Fq '.virtual-assistant-chat {' "$styles"
rg -Fq '.virtual-assistant-chat__select {' "$styles"
rg -Fq 'right: var(--virtual-assistant-right, 32px);' "$styles"
rg -Fq 'bottom: var(--virtual-assistant-bottom, 60px);' "$styles"
rg -Fq 'font-size: 10px; line-height: 16px;' "$styles"
rg -Fq 'font: 500 14px/22px inherit;' "$styles"
rg -Fq 'font: 700 14px/22px inherit;' "$styles"
rg -Fq 'data-virtual-assistant-chat-select-instrument' "$app"
rg -Fq 'data-virtual-assistant-instrument-modal' "$app"
rg -Fq 'data-virtual-assistant-instrument-continue' "$app"
rg -Fq 'virtual-assistant-chat--selected' "$app"
rg -Fq 'Instrument selected:' "$app"
rg -Fq 'Type your prompt here' "$app"
rg -Fq 'const chatTimestamp = (date = new Date()) =>' "$app"
rg -Fq 'data-virtual-assistant-conversation-confirm' "$app"
rg -Fq 'Create new chat?' "$app"
rg -Fq 'Close chat?' "$app"
rg -Fq 'Prototype route 1' "$app"
rg -Fq 'Instr. part of the user account' "$app"
rg -Fq 'Instr. not part of the user account' "$app"
rg -Fq 'Select user prompt route' "$app"
rg -Fq 'Enter serial number 1099955 (part of user account)' "$app"
rg -Fq 'Enter serial number 1099965 (not part of user account)' "$app"
rg -Fq 'My instrument shows an Error 33 message' "$app"
rg -Fq 'When does coverage end for my instrument' "$app"
rg -Fq 'Why sky is blue' "$app"
rg -Fq 'openUserPromptRouteDialog();' "$app"
rg -Fq 'virtual-assistant-route-dialog flows-dialog' "$app"
rg -Fq 'Prototype-only route selector' "$app"
rg -Fq 'virtual-assistant-route-dialog__eyebrow' "$app"
rg -Fq '.virtual-assistant-route-dialog { width: min(560px, calc(100vw - 32px));' "$styles"
rg -Fq '.virtual-assistant-route-dialog__eyebrow {' "$styles"
rg -Fq '.virtual-assistant-route-dialog .flow-link { min-height: 56px;' "$styles"
rg -Fq 'if (createsNewChat || action === "close") {' "$app"
rg -Uq 'const renderWelcome = \(\) => \{\n    selectedSerial = null;' "$app"
rg -Fq '.virtual-assistant-confirmation-modal {' "$styles"
rg -Fq 'panel.append(conversationConfirmation);' "$app"
rg -Fq 'virtual-assistant-confirmation-modal__overlay' "$app"
rg -Fq '.virtual-assistant-confirmation-modal { position: absolute;' "$styles"
rg -Fq 'align-items: end; justify-items: center; padding: 16px 16px 132px;' "$styles"
rg -Fq 'Minimize chat</span>' "$app"
rg -Fq 'Close chat</span>' "$app"
rg -Fq '.virtual-assistant-chat__action-tooltip {' "$styles"
rg -Fq '.virtual-assistant-chat__actions button > img { width: 16px; height: 16px; }' "$styles"
rg -Fq '.virtual-assistant-chat__action-tooltip { position: absolute; z-index: 1001; bottom: calc(100% + 10px);' "$styles"
rg -Fq '.virtual-assistant-chat { position: fixed; z-index: 1000;' "$styles"
rg -Fq 'overflow: visible; border: 1px solid #6058df;' "$styles"
rg -Fq '.virtual-assistant-chat.is-collapsed {' "$styles"
rg -Fq 'bottom: calc(var(--virtual-assistant-bottom, 20px) - 20px);' "$styles"
rg -Fq 'border-radius: 8px 8px 0 0;' "$styles"
rg -Fq '.virtual-assistant-chat.is-collapsed .virtual-assistant-chat__header { min-height: 46px; align-items: center; justify-content: flex-start; gap: 8px;' "$styles"
rg -Fq -- '-webkit-mask: url("assets/icons/assistant-icon.svg") center / contain no-repeat;' "$styles"
rg -Fq -- '-webkit-mask: url("assets/icons/directions/chevron up/size=24px, style=bold.svg") center / contain no-repeat;' "$styles"
rg -Fq 'chevron up/size=24px, style=bold.svg' "$app"
rg -Fq 'panel.addEventListener("click", (event) => {' "$app"
rg -Fq 'if (panel.classList.contains("is-collapsed") && !event.target.closest("[data-virtual-assistant-chat-collapse]")) setCollapsed(false);' "$app"
rg -Fq '.virtual-assistant-instrument-modal {' "$styles"
rg -Fq 'virtual-assistant-instrument-modal__filter' "$app"
rg -Fq '.virtual-assistant-instrument-modal [data-va-filter-trigger] .msf__trigger' "$styles"
rg -Fq 'virtual-assistant-instrument-modal__filter-host' "$app"
rg -Fq 'data-virtual-assistant-applied-filters' "$app"
rg -Fq 'data-virtual-assistant-clear-filters' "$app"
rg -Fq 'const updateAppliedFilters = () =>' "$app"
rg -Fq '.virtual-assistant-instrument-modal__applied-filters' "$styles"
rg -Fq '.virtual-assistant-instrument-modal__applied-filters .msf__clear { display: none; }' "$styles"
rg -Fq 'color: #0071d0;' "$styles"
rg -Fq 'const catalogFilter = new window.MultiSelectFilter' "$app"
rg -Fq 'data-virtual-assistant-instrument-add' "$app"
rg -Fq 'wireVirtualAssistantInstrumentTooltips' "$app"
rg -Fq 'let selectedSerial = null;' "$app"
rg -Fq 'data-virtual-assistant-instrument-continue disabled' "$app"
rg -Fq 'updateContinueState();' "$app"
rg -Fq 'afterSystem = instruments.filter((instrument) => instrument.serial === "SN98356W")' "$app"
rg -Fq '${selectedSerial === instrument.serial ? "checked" : ""}' "$app"
rg -Fq '.virtual-assistant-instrument-modal [data-va-filter-trigger] .msf__menu' "$styles"
rg -Fq '.virtual-assistant-instrument-modal__tooltip' "$styles"
rg -Fq '.virtual-assistant-instrument-modal th { font-weight: 500; }' "$styles"
rg -Fq '.virtual-assistant-instrument-modal input[type="radio"]:checked { border-color: #0071d0; background: #0071d0; box-shadow: inset 0 0 0 4px #fff; }' "$styles"
! rg -Fq '.virtual-assistant-instrument-modal td:nth-child(4), .virtual-assistant-instrument-modal td:nth-child(5)' "$styles"
rg -Fq '.virtual-assistant-instrument-modal__content > footer .mi-dialog-button--primary:disabled' "$styles"
rg -Fq '.virtual-assistant-chat__composer {' "$styles"
rg -Fq '.virtual-assistant-chat--selected .virtual-assistant-chat__body { display: flex; align-items: stretch; flex-direction: column; padding: 0; }' "$styles"
rg -Fq 'What can I help you with regarding your selected instrument?' "$app"
rg -Fq "Ask a question about setup, operation, maintenance, troubleshooting, or other topics covered in your instrument's operator manual." "$app"
rg -Fq 'virtual-assistant-chat__assistant-response' "$app"
rg -Fq 'renderSelected(option.dataset.virtualAssistantRouteOption);' "$app"
rg -Fq '.virtual-assistant-chat__assistant-message {' "$styles"
rg -Fq 'assets/icons/ai-badge.svg' "$app"
test -f "$root/assets/icons/ai-badge.svg"
rg -Fq '.virtual-assistant-chat__conversation { display: flex; height: 0; min-height: 0; flex: 1; flex-direction: column; justify-content: flex-start; overflow-x: hidden; overflow-y: auto;' "$styles"
rg -Fq '.virtual-assistant-chat__conversation > * { flex: 0 0 auto; }' "$styles"
rg -Fq '.virtual-assistant-chat__conversation > .virtual-assistant-chat__timestamp { margin-top: auto; }' "$styles"
rg -Fq 'conversation.scrollTop = conversation.scrollHeight;' "$app"
rg -Fq 'Instrument selected is not part of your account, Please add the instrument to proceed' "$app"
rg -Fq 'data-virtual-assistant-account-add' "$app"
rg -Fq 'setRoute("add-instruments")' "$app"
rg -Fq '.virtual-assistant-chat__account-add {' "$styles"

echo 'Virtual assistant chat is wired.'
